"""50 curated writing tips, rotated one per session via /coach-tip."""

TIPS: list[tuple[str, str]] = [
    ("Cut 'very' and find a stronger word: 'very tired' is 'exhausted'.", "word-choice"),
    ("Lead with the point. Put your conclusion in the first sentence, then support it.", "structure"),
    ("Prefer active voice: 'The team shipped the feature', not 'The feature was shipped'.", "clarity"),
    ("If a sentence runs past 25 words, look for a place to split it.", "clarity"),
    ("Read your draft aloud. Anywhere you stumble, your reader will too.", "editing"),
    ("Delete your first paragraph and see if the piece still works. It usually does — and starts stronger.", "editing"),
    ("One idea per sentence. One theme per paragraph.", "structure"),
    ("Replace 'there is/there are' openings with a concrete subject and verb.", "clarity"),
    ("Adverbs often prop up weak verbs. 'Ran quickly' is 'sprinted'.", "word-choice"),
    ("Specific beats general: '43% faster' persuades more than 'much faster'.", "persuasion"),
    ("Write the first draft fast and badly. Editing bad text is easier than writing perfect text.", "habit"),
    ("End emails with one clear ask. Two asks get half the response rate.", "professional"),
    ("Avoid hedges like 'I think', 'maybe', 'sort of' unless uncertainty is the point.", "confidence"),
    ("Use concrete nouns: 'the login page' paints a picture; 'the relevant component' doesn't.", "clarity"),
    ("Vary sentence length. Short sentences punch. Longer ones give the reader room to breathe and absorb.", "rhythm"),
    ("Cut throat-clearing openers: 'It's worth noting that', 'Basically', 'In order to'.", "wordiness"),
    ("The last word of a sentence carries the most weight. Put the key word there.", "rhythm"),
    ("Numbers under ten are usually spelled out; 10 and above use digits. Pick a rule and stay consistent.", "mechanics"),
    ("When you write 'and' between two verbs, check whether one of them is doing any work.", "wordiness"),
    ("Swap 'utilize' for 'use'. The longer word never adds meaning, only syllables.", "word-choice"),
    ("Paragraphs online should be 1-3 sentences. Wall-of-text kills reading on a screen.", "formatting"),
    ("Write headlines and openers last, after you know what the piece actually says.", "process"),
    ("A colon sets up a payoff: use it when the second half delivers on the first.", "mechanics"),
    ("'Which' adds information; 'that' restricts it. 'The car that is red' picks one; 'the car, which is red' describes it.", "grammar"),
    ("Show the stakes early. Readers finish what they know matters to them.", "persuasion"),
    ("Kill your favorite sentence if it doesn't serve the piece. Save it in a file for later.", "editing"),
    ("Transitions like 'however' and 'therefore' work best early in the sentence, not buried mid-clause.", "structure"),
    ("Don't stack prepositions: 'the results of the analysis of the data from the survey' → 'the survey results'.", "wordiness"),
    ("Anchor abstract claims with one example. One is enough; three is a list.", "persuasion"),
    ("Use 'you' more than 'I' in persuasive writing. Readers care about their problem, not your process.", "persuasion"),
    ("Semicolons join two complete sentences that belong together; if either half can't stand alone, don't use one.", "mechanics"),
    ("In a list of three, put the strongest item last.", "rhythm"),
    ("Check every 'it' and 'this': can the reader tell instantly what it refers to?", "clarity"),
    ("Write drunk on ideas, edit sober on structure. Separate the two passes.", "process"),
    ("Passive voice hides the actor. If you don't know who did it, that's a research gap, not a style choice.", "clarity"),
    ("'Really', 'just', 'quite', 'rather' — search and delete. The sentence almost always improves.", "wordiness"),
    ("Front-load emails: recipient should get the point from the first line and the subject alone.", "professional"),
    ("Parallel structure makes lists scannable: start every bullet with the same part of speech.", "structure"),
    ("If two words fight for the same job ('completely finished', 'end result'), cut one.", "wordiness"),
    ("Metaphors clarify or they decorate. Keep the first kind, cut the second.", "style"),
    ("Strong verbs beat adjective piles: 'the deadline loomed' > 'the very close deadline'.", "word-choice"),
    ("Read competitors' writing and mark where you got bored. Never do that thing.", "process"),
    ("Contractions make writing warmer. Formal doesn't have to mean stiff — unless it's academic work.", "tone"),
    ("Start sentences with the subject when in doubt. Fancy openers are a garnish, not the meal.", "clarity"),
    ("Every 'etc.' is a missed chance to either finish the list or cut it to the best examples.", "precision"),
    ("Questions engage, but one per section. A pile of rhetorical questions reads as filler.", "style"),
    ("Write your conclusion first as a compass. You can rewrite it after the journey.", "process"),
    ("When a sentence needs three commas, it usually wants to be two sentences.", "clarity"),
    ("Jargon is fine for insiders, deadly for mixed audiences. Know which one you're writing for.", "audience"),
    ("Track your own tics. Everyone has three crutch words — find yours and budget them.", "habit"),
]
